### ISSUE TITLE
pytz.exceptions.UnknownTimeZoneError: ''

### ISSUE THREAD

**Issue by ps6000** [ModusVivendi/twitter-contest#14]
Getting this error of unknown timezone with pytz looks like its after calling the scheduler in main.py?

Traceback (most recent call last):
  File "main.py", line 430, in <module>
    scheduler = BlockingScheduler()
  File "/usr/local/lib/python3.4/dist-packages/apscheduler/schedulers/base.py", line 61, in **init**
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.4/dist-packages/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "/usr/local/lib/python3.4/dist-packages/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib/python3.4/dist-packages/tzlocal/unix.py", line 122, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.4/dist-packages/tzlocal/unix.py", line 61, in _get_localzone
    return pytz.timezone(etctz.replace(' ', '_'))
  File "/usr/local/lib/python3.4/dist-packages/pytz/**init**.py", line 180, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: ''

**Comment by AuxProc** [comment]
It looks like get_localzone() is not able to retrieve the local timezone from your host necessary for BlockingScheduler.  Not sure why that is atm.  I think as a workaround, you could try to edit line 430 in main.py to read something like: `scheduler = BlockingScheduler(timezone='MST')`.  Use your timezone instead of MST.
