### ISSUE TITLE
How to install? (Front page instructions don't work)

### ISSUE THREAD

**Issue by Seroria** [ModusVivendi/twitter-contest#18]
Hi @ModusVivendi , I've been trying this for 3 days and have probably spent 5-6h trying to do this to no avail. Here is my current situation;
- I have Python3.5 installed
- I have a clean copy of TwitterAPI as I just deleted and reinstalled it
- I have a folder called twitter-contest-master on my desktop and it contains the following; .travis.yml (Untouched), config.json (Originally ...json.example and now filled out with MY access token etc.), log (Untouched), main.py (Untouched and seems to always have different errors when I run) README.MD, and tests.py.

When I run main.py in this state, I get this error:

```
Traceback (most recent call last):
  File "C:\Users\Lucas Fern\Desktop\twitter-contest-master\main.py", line 424, in <module>
    Config.access_token_secret)
  File "C:\Users\Lucas Fern\AppData\Local\Programs\Python\Python35-32\lib\site-packages\TwitterAPI\TwitterAPI.py", line 44, in __init__
    raise Exception('Missing authentication parameter')
Exception: Missing authentication parameter
```

I've tried what seems like everything but when I edit out an error, I generate a new one. 

I'd be super grateful if you could help as I've already invested quite a bit of time into this project.

Sorry for being a nuisance,
Lucas

**Comment by AuxProc** [comment]
Do you have all four required authentication keys in your config.json?  Double check you did not copy over any empty spaces from the twitter app page.  Your twitter app must have read and write permissions.

**Comment by Seroria** [comment]
@ModusVivendi My config.json looks like this (I've censored the first few letters of the keys but I'm sure they are all just letters/numbers):

```
{
        "search-queries": ["RT to win", "Retweet and win"],
        "follow-keywords": [" follow ", " follower "],
        "fav-keywords": [" fav ", " favorite ", " like "],
        "scan-update-time": 5400,
        "daily-tweets": 300,
        "rate-limit-update-time": 300,
        "min-ratelimit": 10,
        "min-ratelimit-retweet": 20,
        "min-ratelimit-search": 40,
        "clear-queue-time": 43200,
        "min-posts-queue": 60,
        "blocked-users-update-time": 300,
        "max-follows": 1950,
    "consumer-key": "***raXggBjRcKhtgZ31VaRhkZ",
    "consumer-secret": "***BXCb1lywjmJcGiiaMMdZPNaAOu0ffp7pQAXy4rIT4ljBaXs",
    "access-token-key": "***290619615436800-***ULh8IXXTPWlQL8IRlUycLykQImZK",
    "access-token-secret": "***Docr4I8qnl5gtlTtuTWgYSMRwPt5wPnvg2sR125QXC"
}
```

The twitter app has priveleges to read, write and access direct message access.

**Comment by AuxProc** [comment]
Looking at the TwitterAPI, that error is only supposed to be raised when not all your authentication keys are there.  Since it looks like your keys are there, something must be happening when the config file is loaded or the values are getting reset after its loaded.  

Would you mind trying Python 3.4 instead of 3.5?

**Comment by Seroria** [comment]
@ModusVivendi Unfortunately still no luck, I have a screenshot showing me running main.py in the Python v3.4.4 shell. Same error but the screenshot also shows both lines that the error refers to in hopes of that showing a potential problem. That's [here](https://gyazo.com/75c038ad6ca67250e2fc7ffa804e0a87), any other ideas?

**Comment by AuxProc** [comment]
Alright, try opening it up this way if you are not already.  Run a command prompt as administrator.  

Change directory into the twitter contest directory: `cd "c:\Users\Lucas Fern\Desktop\twitter-contest-master"`

Run: `c:\Python34\python.exe main.py`

**Comment by Seroria** [comment]
@ModusVivendi Not 100% sure I did that right but I'm certain I ran it as Admin and after using your commands it seems to arrive at the same conclusion. [This](https://gyazo.com/55fe77b0d01855b780a0d52f1c737403) is what I executed in CMD and the results. I could try starting this whole thing from scratch by removing all traces of Python from my PC and reinstalling contest-bot, Python etc. but I've already tried something of the sort so not too sure that'd help...
