### ISSUE TITLE
Issue with ASCII character out of range

### ISSUE THREAD

**Issue by kylemarham** [ModusVivendi/twitter-contest#23]
`2016-09-26 14:03:26,911 - ERROR - Could not connect to TwitterAPI - are your credentials correct?
Traceback (most recent call last):
  File "main.py", line 392, in ScanForContests
    original_screen_name,text))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 143: ordinal not in range(128)
2016-09-26 14:03:26,920 - INFO - Getting new results for: Retweet and win
2016-09-26 14:03:27,951 - ERROR - Could not connect to TwitterAPI - are your credentials correct?
Traceback (most recent call last):
  File "main.py", line 406, in ScanForContests
    logger.info("{0} - {1} : {2}".format(id, screen_name, text))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 2: ordinal not in range(128)`

**Comment by AuxProc** [comment]
Please ensure that the config.json file is being saved in UTF-8.

**Comment by flicht** [comment]
same issue as above. the config file is in utf-8. Cheers
